---

concurrency: ${{ github.event.repository.name }}

name: Destroy

"on":
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/GitHub
          aws-region: ${{ secrets.AWS_REGION }}
      - run: |
          aws cloudformation delete-stack --stack-name=${{ github.event.repository.name }}
          aws cloudformation wait stack-delete-complete --stack-name=${{ github.event.repository.name }}
